Feature/login
Moorisong/Football-Player-Tamagotch pull request #38
Opened 2023-05-24 07:03 UTC by Moorisong

## 내용

- 로그인 요청 전 valid 체크 진행
- 로그인 이후 결과 처리
- 각 요소 스타일링

2023-05-24 07:19 UTC, the1975 commented
conflict 있네요, rebase를 하거나 dev -> feature/login 역머지를 한번 해서 최신화 하는게 좋아보입니다. rebase 써보는걸 추천합니다.

2023-05-24 07:19 UTC, the1975 commented
PR 제목과 내용을 조금 더 상세하게 써주세요.

2023-05-24 07:30 UTC, the1975 requested changes

2023-05-24 07:30 UTC, the1975 commented on package.json
> -    "eslint": "^7.32.0",
eslint는 왜 지워졌나요?

2023-05-24 07:30 UTC, the1975 commented on src/routes/LogIn/LogIn.jsx
> +        return console.log('Error---->', result.errorMsg)
불필요한 콘솔이라면 지워두는게 좋겠네요.

2023-05-24 07:30 UTC, the1975 commented on src/routes/LogIn/LogIn.jsx
> +            <p> ID</p>
`ID` 앞에 공백 한칸이 들어간 이유가 있나요?

2023-05-24 07:30 UTC, the1975 commented on src/routes/LogIn/LogIn.jsx
> +            { invailidMsg.indexOf('ID') > -1 && <p className={styles.inputTextUnder}> {invailidMsg} </p> }
`ID`와 아래쪽에 `비밀번호` 에러 메세지 노출조건 방식을 바꾸는게 좋아보입니다.
객체 형태로 에러 매핑을 하고, 에러 객체에 해당하는 필드에 텍스트가 있을 때 보여주는것도 괜찮겠네요.

```tsx
// 아이디만 입력하지 않은 경우
const invalidMessage = {
  id: '',
  pw: ''
}

...

if (!id) invalidMessage.id = '아이디를 입력해주세요.'

...

{ invalidMessage.id && <p className={styles.inputTextUnder}> {invalidMessage.id} </p>}

```

2023-05-24 15:57 UTC, Moorisong commented on src/routes/LogIn/LogIn.jsx
> +    if (!id && !pw) return 'none'
최초 로드 시에 'ID를 입력해주세요.', '비밀번호를 입력해주세요.' 둘 다 표시되는걸 원하지 않았었는데,
둘 다 노출되게 하는 편이 나을까요?

2023-05-24 15:57 UTC, Moorisong commented on src/routes/LogIn/LogIn.jsx
> +      pw: pw,
오 감사합니다.

2023-05-24 15:57 UTC, Moorisong commented on src/routes/LogIn/LogIn.jsx
> +        return console.log('Error---->', result.errorMsg)
넵

2023-05-24 15:58 UTC, Moorisong commented on src/routes/LogIn/LogIn.jsx
> +            <p> ID</p>
오탈자입니다. 수정하도록 하겠습니다.

2023-05-24 16:04 UTC, Moorisong commented on src/routes/LogIn/LogIn.jsx
> +            { invailidMsg.indexOf('ID') > -1 && <p className={styles.inputTextUnder}> {invailidMsg} </p> }
감사합니다. 에러 메시지들을 객체에 담고, id, pw 변수 값을 기준으로 에러 메시지를 가져오도록 하겠습니다.

2023-05-25 07:59 UTC, the1975 requested changes

2023-05-25 07:59 UTC, the1975 commented on src/routes/LogIn/LogIn.jsx
> +      if (result.resultMsg === 'logIn_success') return navigate('/Main')
url에는 대문자를 잘 사용하지 않습니다.
`navigate('/main')`

2023-05-25 07:59 UTC, the1975 commented on src/routes/LogIn/LogIn.jsx
> +      if (result.resultMsg === 'notFoundID' || result.resultMsg === 'notFoundPw') return alert('ID나 비밀번호가 올바르지 않습니다.')
`resultMsg`보다는 `errorCode`가 적절하지 않을까요?
메세지보다는 코드형식이네요.

2023-05-25 15:14 UTC, the1975 approved these changes

2023-05-25 15:15 UTC, merged